// <auto-generated />
using System;
using MELIPARCIAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MELIPARCIAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MELIPARCIAL.Models.ConversionHistorial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaConversion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MonedaConvertida")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MonedaOriginal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("MontoConvertido")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MontoOriginal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TasaCambio")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("ConversionHistoriales");
                });

            modelBuilder.Entity("MELIPARCIAL.Models.Remesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EstadoTransaccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("MontoEnviado")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MontoFinal")
                        .HasColumnType("numeric");

                    b.Property<string>("NombreDestinatario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreRemitente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaisDestino")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaisOrigen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TasaCambio")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Remesas");
                });
#pragma warning restore 612, 618
        }
    }
}
